module.exports = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'DC': 'District of Columbia',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
    'ALABAMA': 'Alabama',
    'ALASKA': 'Alaska',
    'ARIZONA': 'Arizona',
    'ARKANSAS': 'Arkansas',
    'CALIFORNIA': 'California',
    'COLORADO': 'Colorado',
    'CONNECTICUT': 'Connecticut',
    'DELAWARE': 'Delaware',
    'DIST OF COL': 'District of Columbia',
    'FLORIDA': 'Florida',
    'GEORGIA': 'Georgia',
    'HAWAII': 'Hawaii',
    'IDAHO': 'Idaho',
    'ILLINOIS': 'Illinois',
    'INDIANA': 'Indiana',
    'IOWA': 'Iowa',
    'KANSAS': 'Kansas',
    'KENTUCKY': 'Kentucky',
    'LOUISIANA': 'Louisiana',
    'MAINE': 'Maine',
    'MARYLAND': 'Maryland',
    'MASSACHUSETTS': 'Massachusetts',
    'MICHIGAN': 'Michigan',
    'MINNESOTA': 'Minnesota',
    'MISSISSIPPI': 'Mississippi',
    'MISSOURI': 'Missouri',
    'MONTANA': 'Montana',
    'NEBRASKA': 'Nebraska',
    'NEVADA': 'Nevada',
    'NEW HAMPSHIRE': 'New Hampshire',
    'NEW JERSEY': 'New Jersey',
    'NEW MEXICO': 'New Mexico',
    'NEW YORK': 'New York',
    'NORTH CAROLINA': 'North Carolina',
    'NORTH DAKOTA': 'North Dakota',
    'OHIO': 'Ohio',
    'OKLAHOMA': 'Oklahoma',
    'OREGON': 'Oregon',
    'PENNSYLVANIA': 'Pennsylvania',
    'RHODE ISLAND': 'Rhode Island',
    'SOUTH CAROLINA': 'South Carolina',
    'SOUTH DAKOTA': 'South Dakota',
    'TENNESSEE': 'Tennessee',
    'TEXAS': 'Texas',
    'UTAH': 'Utah',
    'VERMONT': 'Vermont',
    'VIRGINIA': 'Virginia',
    'WASHINGTON': 'Washington',
    'WEST VIRGINIA': 'West Virginia',
    'WISCONSIN': 'Wisconsin',
    'WYOMING': 'Wyoming'
};